drop table if exists admin CASCADE;

create table admin
(
 id bigint generated by default as identity,
 username varchar(255),
 password varchar(20),
 hp varchar(20),
 profile_img varchar(255),
 primary key (id)
);
